log_timestamp: false
log_caller: false

backend_dir: ./

backends:
  rest:
    url: http://localhost:8000/api
    users_path: /ldap/user
    groups_path: /ldap/group
    auth_token: 42a698e62cdd10356ff735a24ea2d6854fe910fe
    http_request_timeout: 30s
  file:
    users_path: users.json
    groups_path: groups.json

respect_control_criticality: true

users_ou_name: users
groups_ou_name: groups

use_tls: false
server_cert: server.crt
server_key: server.key

callback_listen_addr: localhost:8080
